export const LINK_ACCOUNTS_SCENE_ID = 'LINK_ACCOUNTS_SCENE_ID';
export const UNLINK_ACCOUNTS_SCENE_ID = 'UNLINK_ACCOUNTS_SCENE_ID';
export const LINK_STATUS_SCENE_ID = 'LINK_STATUS_SCENE_ID';

export const GRILL_NOTIFICATIONS_BOT_NAME = 'grill-notifications-bot';

export const TELEGRAM_TEMPORARY_LINKING_ID_EXPIRATION_TIME_MINS_DEFAULT = 10;
